### ISSUE TITLE
Local Storage Example

### ISSUE THREAD

**Issue by ChrisWellsWood** [gren-lang/example-projects#8]
Hello, thanks for your work on Gren, it looks like a really exciting project. I was looking through the examples and noticed that there was one for local storage, which I was pleased to see, especially with the tasks api. I can't get this to work on my computer as the `LocalStorage` module is missing and I can't find it in any of the Gren repos. Is there any way to install this? @aaalvik I think you provided the example.

**Comment by robinheghan** [comment]
Hi.

Unfortunately, the `LocalStorage` API isn't finished yet. It's under development though, and we hope to finish it in H2 2022.

**Comment by ChrisWellsWood** [comment]
No worries, I'll revisit this later in the year!

**Comment by robinheghan** [comment]
The `web-storage` package has now been released, and the example has been updated :)
